### ISSUE TITLE
Getting 3D world position of mouseX and mouseY on specific plane

### ISSUE THREAD

**Issue by nevahid** [diwi/p5.EasyCam#10]
hi everybody, i'm badly stuck here trying to solve the title of this issue... i tried so many different algorithms but i can't get it right... i don't know what do to this about this one... can anyone please help?
and i guess it might be a good additional function for this library... it would really appreciate any kind of help...
@diwi and anyone who can help!
thanks again

**Comment by jwdunn1** [comment]
This sketch may help...especially the screenToWorld() method in the DwCoordinateTransform class. https://www.openprocessing.org/sketch/496458

**Comment by nevahid** [comment]
Wow... thank you very much... i'm diving into it to find my solution... in my own solution i could get the mouse position right when there was no rotation, but if i rotate the scene, 3d coordinates differ from mouse coordinates... 
thanks again... i will check that right now :-)

**Comment by nevahid** [comment]
@jwdunn1 
hi again dear james, well i tried to figure your project, but it was way different that p5.easycam... anyway i looked at your conversion method and they both looked identical algorithmically... i will post my code here, maybe i've missed something. thanks for your kind help:

the function getResultMouse is the main method... toRealProject(mx,my) get the mouse X and mouse Y position and produce a ray in that direction.. and the getRayPoint(ray) takes the ray and gives the amount of ray (t) where the ray meets a specific plane (here y=-100)... and then getResultMouse  takes the ray and the t and gives out the answer... if i look forward ( i mean at (0,0,-1)) everything works great and as expected, but when i rotate the screen, there seems i'm missing something there as the projected vertice is not under mouse coordinates... please help me :-(

```
function toRealProject(mx,my)
{
	let x=(2*mx)/width -1;
	let y= 1- (2*my)/height;
	let z=-1;
	let vecRayClip=[x,y,z,1];
	let PMatrix=RENDERER.uPMatrix.copy();
	let invPM=matrix_invert(PMatrix);
	let vecRayEye=multiply(invPM,vecRayClip);
	let vecRayEyeNew=[vecRayEye[0],vecRayEye[1],-1,0];
	let VMatrix=RENDERER.uMVMatrix.copy();
	let invVM=matrix_invert(VMatrix);
	let multEYEVM=multiply(invVM,vecRayEyeNew);
	let w_inv = 1/multEYEVM[3];
	let vecRayWorld=createVector(multEYEVM[0]*w_inv,multEYEVM[1]*w_inv,multEYEVM[2]*w_inv);
	vecRayWorld.normalize();
	return vecRayWorld;
}

function getRayPoint(ray) {
	let normal = createVector(0,1,0);
	let fixedpoint= createVector(0,-100,0); //seems this is better!!
	let mousepos= mainCam.getPosition();
	let denom = p5.Vector.dot(ray,normal);
	let vecmf= p5.Vector.sub(fixedpoint,mousepos);
	let nom= p5.Vector.dot(vecmf,normal);
	return nom/denom;
}

function getResultMouse() {
	let thisvecray=toRealProject(mouseX,mouseY);
	let t=getRayPoint(thisvecray);
	let tn=p5.Vector.mult(thisvecray,t);
	let campos=createVector(mainCam.getPosition()[0],mainCam.getPosition()[1],mainCam.getPosition()[2]);
	let answer= p5.Vector.add(campos,tn);
	return answer;
}
```

**Comment by nevahid** [comment]
hi to those people reading this... i found the solution, and it was unbelievably strange!! i just commented part the inverted the view matrix... so i just multiplied the view matrix into my vecRayEyeNew... and now everything is working as expected!!! sooo strange...
