### ISSUE TITLE
Submit to be included on the p5.js website's libraries page

### ISSUE THREAD

**Issue by bmoren** [diwi/p5.EasyCam#14]
Submit to be included on the p5.js website's libraries page

I feel like this would be helpful, especially to get in front of student's eyes.  In my classes, students have a hard time traversing the endless JavaScript library terrain, and having a concise starting location like the p5 website is super helpful. 

Submit to be included here:
https://docs.google.com/forms/d/e/1FAIpQLSdWWb95cfvosaIFI7msA7XC5zOEVsNruaA5klN1jH95ESJVcw/viewform

**Comment by jwdunn1** [comment]
This repo appears to be abandoned. **The currently supported version of p5.EasyCam is now available as a community library on the p5.js website!** The new release works correctly with p5.js v0.9.0 and includes a fix for HUD. Also, in the Quick Reference section of the readme, there is a link to a new tutorial series on how to work with EasyCam in OpenProcessing. Any new issues should be posted in the new repo here: https://github.com/freshfork/p5.EasyCam
