### ISSUE TITLE
Codesandbox "n.camera is not a function"

### ISSUE THREAD

**Issue by carstenheisterkamp** [diwi/p5.EasyCam#20]
Hi, I have the "Camera is not a function error"  issue similar to 

https://github.com/diwi/p5.EasyCam/issues/11
https://github.com/diwi/p5.EasyCam/issues/5

in codesandbox. 

`p5.easycam.min.js:1 Uncaught TypeError: n.camera is not a function`

The  fix from https://github.com/diwi/p5.EasyCam/issues/5 solves it but may be you can look into this. Thanks C.

**Comment by jwdunn1** [comment]
Here's a working version: https://codesandbox.io/s/clever-archimedes-lcnqi
Be sure to use the current version of p5.EasyCam found here: https://github.com/freshfork/p5.EasyCam
