### ISSUE TITLE
what is mouseDragPan()?

### ISSUE THREAD

**Issue by nevahid** [diwi/p5.EasyCam#8]
hi everybody... does anyone know what is mouseDragPan()? i don't understand this: "implemented pan-cb for mousedrag/touch handler." as a description for this function...
anyway i want to set some constraints on mousewheel zoom, such that disable zooming in or out more than a defined value. i thought  mouseDragPan might be related to it... thanks people....

**Comment by jwdunn1** [comment]
mouseDragPan() implements the mouse's middle button dragging operation which pans the scene (no scaling). You might investigate mouseWheelZoom() and try constraining cam.dampedZoom.addForce().

**Comment by nevahid** [comment]
thanks for your response. but how can i use it? i didn't find any example regarding these functions... thank you so much again...

**Comment by nevahid** [comment]
ok! i finally found a solution for disabling mouse wheel zoom, i just added this function to the main js file at line 536:

removeMouseWheelListener(){
	var cam = this.cam;
    var mouse = cam.mouse;
	cam.detachListener(mouse.wheel     );
  }

javascript is pretty fun :-P ;-)
