### ISSUE TITLE
HighDPI handling

### ISSUE THREAD

**Issue by nevahid** [diwi/p5.EasyCam#9]
hi there, it seems there is a problem with high DPI displays. i don't know if it's related to easycam or p5.js or even webgl itself. any suggestion? any idea?
@diwi thanks in advance...

**Comment by jwdunn1** [comment]
Do you have an example? I am not seeing any problems on high DPI devices. For instance, the following sketch runs as designed on desktop, tablet, and mobile (including iPhone 7, LG K10): https://www.openprocessing.org/sketch/645473 (Responds to multi-touch, drag, spread, etc.)

**Comment by nevahid** [comment]
hi again, thanks for your response, i found it to be related to p5.js and webgl. I used pixelDensity(1) and it was solved. although pixel density is better to be set to pixel density of client device. 
thanks anyway

**Comment by jwdunn1** [comment]
FYI, the example I listed above uses p5.js v0.7.3, in WEBGL rendering mode, and pixelDensity(2). No issues. Which version of p5.js are you testing?

**Comment by nevahid** [comment]
i tested on v0.7.3, it was ok on Low DPI laptop, but on high DPI screen, the canvas was almost half the window width, when i set pixelDensity to 1, it was fit to window, but yet zoom mult differs on different browsers on high DPI screen.
